apiVersion: v1
data:
  password: MWYyZDFlMmU2N2Rm
  test-key: gAAAAABe5tzEW5EhFZgBuMpoK0T8lJLfNkBZCd5I5Ea6YGwk5qjrqjKuUFDu_mtDHgHmHqX44Q70pnliJuVjvCd9fq2soWTnxQ==
  test-key1: gAAAAABe5jQchWyr0TFnDbbEIvrlxPR9cpwqyz6MhZOdF9uibgpWrF9O7kwUY608xzCFgnc1vAUFWROx9xSA0nIWcAgsQxFFXw==
  username: YWRtaW4=
kind: Secret
metadata:
  name: mysecret
type: Opaque
