apiVersion: v1
data:
  password: MWYyZDFlMmU2N2Rm
  test-key: gAAAAABe5jY5p-z5kICKssl_lhhQ_hD2PGhEq-BioOqoGE8DaLEnp-5umhc9nEmSN2S9FpJTyABi9-7YvUxh0CEJ8gLWWGhgXg==
  test-key1: gAAAAABe5jQchWyr0TFnDbbEIvrlxPR9cpwqyz6MhZOdF9uibgpWrF9O7kwUY608xzCFgnc1vAUFWROx9xSA0nIWcAgsQxFFXw==
  username: YWRtaW4=
kind: Secret
metadata:
  name: mysecret
type: Opaque
