apiVersion: v1
data:
  password: MWYyZDFlMmU2N2Rm
  test-key: dGVzdC12YWx1ZQo=
  test-key1: gAAAAABe5jQchWyr0TFnDbbEIvrlxPR9cpwqyz6MhZOdF9uibgpWrF9O7kwUY608xzCFgnc1vAUFWROx9xSA0nIWcAgsQxFFXw==
  username: YWRtaW4=
kind: Secret
metadata:
  name: mysecret
type: Opaque
